name: Zip Resource Pack

on:
  push:
    branches:
      - main
      - beta

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create Texturepack Zip
        run: zip -r CreeperTweaks.zip CreeperTweaks/

      - name: Update Main Release
        if: github.ref == 'refs/heads/main'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: latest
          name: "Stable Release (Main)"
          files: CreeperTweaks.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Update Beta Release
        if: github.ref == 'refs/heads/beta'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: beta-latest
          name: "Beta Testing Release"
          prerelease: true
          files: CreeperTweaks.zip
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
